* cl-evdev: a Linux /dev/input driver for CL

  - Future commits will be located here:
  - https://codeberg.org/slimenoseohcee/cl-evdev

  - SlimeNose note: this is a fork of jtgans cl-evdev. The rest of this Readme will remain unchanged until I make more significant changes
  - Note2: The functionality of this project will be extended, to allow me to write a chording input program (cl-uinput will also be used and changed). After that, I may shoot for a full implementation, provided jtgans and other contributors don't extend the functionality of the original repo. 
  - I already have a semi complete chording program, called khordie. Khordie will be rewritten in CL, as I much prefer CL to every other language I have tried
  - There will be an attempt to simplify adding in international layouts

=cl-evdev= is meant to be a drop-dead simple driver for teasing out events from
Linux's /dev/input drivers. It was originally designed for the Navi project, as
part of the silica keyboard handling routines.

Note: this code is by no means complete, and is less than alpha quality code.
I've tested it on SBCL and Ubuntu Linux 3.x as well as the embedded Linux kernel
built for Intel Edison boards, but nothing else.

** Usage

Use your typical ASDF system definition package, be it directly via ASDF, or via
Quicklisp.

** Tested Devices
  - Lenovo Black Silk Keyboard
  - Wacom CTE-440 Tablet
